@startuml
!include https://raw.githubusercontent.com/patrik-csak/one-dark-plantuml-theme/v1.0.1/theme.puml
hide circle
skinparam {
    classAttributeIconSize 0
    packageStyle rectangle
    backgroundColor transparent
}  

class Main {
   + void main()
   + int[] aufgabe1()
   + int[] aufgabe2(int[] arr)
   + int aufgabe3(int[] arr)
   + int aufgabe4(int[] arr)
   + int aufgabe5(int[] arr)
}

@enduml