@startuml
!include https://raw.githubusercontent.com/patrik-csak/one-dark-plantuml-theme/v1.0.1/theme.puml
hide circle
skinparam {
    classAttributeIconSize 0
    packageStyle rectangle
    backgroundColor transparent
}  

class Main {
   {static} + void main()
}

@enduml